# Generated by Django 5.1.7 on 2025-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_customuser_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=100)),
                ('reference_modcod', models.CharField(max_length=100)),
                ('objet', models.TextField()),
                ('date_limite_reponse', models.DateTimeField()),
                ('caution', models.CharField(blank=True, max_length=100, null=True)),
                ('delai_execution', models.CharField(blank=True, max_length=100, null=True)),
                ('prospectus', models.CharField(blank=True, max_length=100, null=True)),
                ('editeur', models.CharField(blank=True, max_length=100, null=True)),
                ('contexte', models.CharField(blank=True, max_length=100, null=True)),
                ('documents_manquants', models.TextField(blank=True, null=True)),
                ('etat_avancement', models.TextField(blank=True, null=True)),
                ('etape_suivante', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
