# Generated by Django 5.1.7 on 2025-07-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='delai_execution',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='prospectus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
