# Generated by Django 5.1.7 on 2025-07-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_rename_objet_project_object'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='object',
            new_name='objet',
        ),
    ]
