# Generated by Django 5.1.7 on 2025-07-11 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_rename_object_project_objet'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
