# Generated by Django 5.1.7 on 2025-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_project_date_creation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='etat_avancement',
        ),
        migrations.AddField(
            model_name='project',
            name='etat_d_avancement',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('PEC', 'PEC'), ('PA', 'PA'), ('PG', 'PG')], default='PEC', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='caution',
            field=models.CharField(choices=[('ELECTRONIQUE', 'ELECTRONIQUE'), ('PHYSIQUE', 'PHYSIQUE')], default='ELECTRONIQUE', max_length=100),
        ),
    ]
