# Generated by Django 5.1.7 on 2025-07-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_remove_project_etat_avancement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('PEC', 'PEC'), ('PA', 'PA'), ('PG', 'PG')], default='PA', max_length=255, null=True),
        ),
    ]
