# Generated by Django 5.1.7 on 2025-07-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0012_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('chef_projet', 'chef_projet'), ('Collaborateur', 'Collaborateur'), ('Stagiaire', 'Stagiaire'), ('Utilisateur_Temporaire', 'Utilisateur_Temporaire')], default='Utilisateur_Temporaire', max_length=255),
        ),
    ]
