# Generated by Django 5.1.7 on 2025-07-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0013_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Chef_projet', 'Chef_projet'), ('Collaborateur', 'Collaborateur'), ('Employe_Integration', 'Employe_Integration'), ('Stagiaire', 'Stagiaire'), ('Utilisateur_Temporaire', 'Utilisateur_Temporaire')], default='Utilisateur_Temporaire', max_length=255),
        ),
    ]
