# Generated by Django 5.1.7 on 2025-07-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0014_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=200)),
                ('référence', models.CharField(blank=True, max_length=150, null=True)),
                ('catégorie', models.CharField(choices=[('Bug technique', 'Bug technique'), ('Erreur de données', 'Erreur de données'), ("Problème d'affichage", "Problème d'affichage"), ('Fonctionnalité manquante', 'Fonctionnalité manquante'), ('Performance lente', 'Performance lente'), ('Problème de collaboration', 'Problème de collaboration'), ('Problème de fichiers / téléchargements', 'Problème de fichiers / téléchargements'), ('Erreurs de permissions', 'Erreurs de permissions'), ('Sécurité / Confidentialité', 'Sécurité / Confidentialité'), ("Problème d'accès / Authentification", "Problème d'accès / Authentification"), ('Autre', 'Autre')], default='Autre', max_length=255)),
                ('priorité', models.CharField(choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Urgent', 'Urgent'), ('Not defined', 'Not defined')], default='Not defined', max_length=100)),
                ('sujet', models.CharField(default='', max_length=500)),
                ('description', models.TextField(default='', max_length=2000)),
                ('piece', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Chef_projet', 'Chef_projet'), ('Collaborateur', 'Collaborateur'), ('Employe_Integration', 'Employe_Integration'), ('Stagiaire', 'Stagiaire'), ('Utilisateur_Confirmé', 'Utilisateur_Confirmé'), ('Utilisateur_Temporaire', 'Utilisateur_Temporaire')], default='Utilisateur_Temporaire', max_length=255),
        ),
    ]
