# Generated by Django 5.1.7 on 2025-07-20 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0015_reclamation_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Résolu', 'Résolu'), ('Non résolu', 'Non résolu')], default='En attente', max_length=50),
        ),
    ]
