# Generated by Django 5.1.7 on 2025-07-20 10:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0016_reclamation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamation',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
