# Generated by Django 5.1.7 on 2025-07-21 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0019_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='montant_caution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
