# Generated by Django 5.1.7 on 2025-07-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0021_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
