# Generated by Django 5.1.7 on 2025-07-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0022_alter_client_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='delai_execution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
