# Generated by Django 5.1.7 on 2025-07-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0023_alter_project_delai_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimation_projet',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='montant_caution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
