# Generated by Django 5.1.7 on 2025-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0024_project_estimation_projet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='technologie',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON'), ('Autre', 'Autre')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('PP', 'PP'), ('PEC', 'PEC'), ('PA', 'PA'), ('PG', 'PG'), ('PAN', 'PAN'), ('PS', 'PS'), ('AU', 'AU')], default='PA', max_length=255, null=True),
        ),
    ]
